# Generated by Django 4.1.5 on 2023-01-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.products')),
            ],
        ),
    ]
